### ISSUE TITLE
Separation of tvm-sys bindgen and tvm-rs

### ISSUE THREAD

**Issue by ehsanmok** [nhynes/tvm-rs#1]
Hi Nick

Since tvm forum seems down, I'd like to make it as our collaborative effort to get things done faster and better. So I've a series of suggestions to make this crate ready for release which I address in separate issue.

From the best practices that I've seen so far in packages providing such bindings such as tensorflow/rust, etc. I think it's better to have a tvm-sys crate independent of tvm-rs for separation of concerns, packaging/release and let bindgen handle the initial ffi itself and we call it from that. [This](https://github.com/ehsanmok/tvm-rust) is what I mean. As a first start, if you don't mind, I can work on make it happen for tvm-rs and replace the existing handle written ffis.

**Comment by nhynes** [comment]
I agree with the idea of separating out the bindgen component, but the point of this library is to allow linking with static TVM modules (i.e. those compiled using `llvm -system-lib`). Since `tvm-sys` [links in `libtvm_runtime.so`](https://github.com/ehsanmok/tvm-rust/blob/master/tvm-sys/build.rs#L7), it can't be used in static-only contexts like embedded devices.

Moreover, this Rust library is actually intended to _replace_ `libtvm_runtime.so` as either a rlib, dylib, or static library depending on the compilation flag.

**Comment by ehsanmok** [comment]
Ah! I see. Now I understand what your goal is which wasn't clear reading your code :blush: So you're heading to more standalone lib and I'm following other runtime apis approach such as java.
